apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-storage
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-etc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-logs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-storage
  resources:
    requests:
      storage: 10Gi