apiVersion: v1
kind: Secret
metadata:
  name: wazuh-credentials
  namespace: monitoring
type: Opaque
data:
  indexer-password: Y2hhbmdlbWU= # base64 encoded "changeme" - change this!
  api-password: Y2hhbmdlbWU= # base64 encoded "changeme" - change this!